// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjqgjicpofuqohqltoeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqcWdqaWNwb2Z1cW9ocWx0b2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNjQ4NDgsImV4cCI6MjA1ODY0MDg0OH0.tMEFwGLHXcPU1nVD7Y89QYPJl7Er_P256z-YJj-gP1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);